### ISSUE TITLE
[FEATURE] Prevent install-completion from failing when command is not available

### ISSUE THREAD

**Issue by dbanty** [tiangolo/typer#75]
When using click-completion in previous versions, if the command was not available in my path when the shell started, it wouldn't cause an error.  I have a variety of command line utilities added to various web apps that I don't want installed globally where I'd have to update them all the time.  Instead, they are available when I'm in the `poetry shell` for that project.

I don't completely understand what click-completion was doing before, but it looks like it was only trying to evaluate completion when calling the command instead of at startup:

```
#compdef openapi-python-client
 _openapi-python-client() {
    eval $(env COMMANDLINE="${words[1,$CURRENT]}" _OPENAPI_PYTHON_CLIENT_COMPLETE=complete-zsh  openapi-python-client)
 }
 if [[ "$(basename -- ${(%):-%x})" != "_openapi-python-client" ]]; then
    compdef _openapi-python-client openapi-python-client
 fi
```

Whereas Typer attempts to evaluate the command immediately:

```
eval "$(_OPENAPI_PYTHON_CLIENT_COMPLETE=source_zsh openapi-python-client)"
```

Would it be possible to add some similar delayed evaluation to Typer?

**Comment by tiangolo** [comment]
Thanks for the report @dbanty ! This should be fixed by #83 , released in `0.1.1`. :rocket: :tada: 

---

More details:

So, the `eval` evaluates a script generated from the program (inside of the `$( ...  openapi-python-client)`), and it, in turn, generates a script similar to the first one above, that is then evaluated there, directly from memory. The new script has a `2> /dev/null` so that the eval is just an empty string if the program is not installed.

<! -- issue-manager: answered -->

**Comment by dbanty** [comment]
I confirmed the error no longer occurs with 0.1.1.  Unfortunately completion still doesn't work for something that's not available in the path at startup, which would be ideal.  I believe that click-completion used to do this?  But I can't confirm because I've already replaced all of my click-completion-using scripts.

As an example of use case, we have several web APIs where I work (one of which is using FastAPI!) and each of them has a CLI for utility functions (e.g. database migrations).  I have these as script entrypoints so that when we're in the poetry environment (e.g. `poetry shell` or the PyCharm terminal) we can just execute the CLI directly.  Actually installing these utilities globally doesn't make a ton of sense because we're constantly updating the projects (and wouldn't want to have to keep updating the globally installed version).

I believe click-completion allowed this to work, where typing `my-command` and pressing tab would do nothing in the base shell, but once I was in `poetry shell` completion would start working. Of course maybe there is a better way of doing this so I welcome any thoughts / suggestions.

**Comment by tiangolo** [comment]
Yep, it makes sense and I agree. In fact, I'm suffering with the same problem as you :joy: 

So yeah, I'm not sure what will be the best approach, but I will definitely update it to work for that use case. :rocket:

**Comment by tiangolo** [comment]
This should be fixed by #92 , released in version `0.2.0` :tada: 

If that solves your problem, you can close the issue :smile:

**Comment by dbanty** [comment]
Hey it works! Thanks! I did have to move the generated lines up in my .zshrc for them to start working. I put it above where I'm sourcing oh-my-zsh.sh because I've seen that be a problem elsewhere.
